version: "3"
silent: true

dotenv: [".env.development"]

env:
  DATABASE_URL: database.db
  VITE_API_URL: http://localhost:8000
  GST_DEBUG_DUMP_DOT_DIR: "{{.ROOT_DIR}}/backend/gst_debug_dot_dir"
  GST_DEBUG: "3"

tasks:
  # TODO: add command to setup the project.
  # 1. install taskfile runtime
  # 2. install rust
  # 3. install gstreamer and related plugins
  # 4. create tmp folder
  # 5. cargo install cargo-tarpaulin

  # ---------------------------- 📦 Dependency Management 📦 ----------------------------

  install:
    desc: "📦 Install dependencies for both front-end and back-end"
    deps:
      - install:frontend
      - install:backend

  install:frontend:
    desc: "📦 Install front-end dependencies"
    dir: web
    cmds:
      - pnpm install

  install:backend:
    desc: "📦 Install back-end dependencies"
    dir: backend
    cmds:
      - cargo fetch
      # - cargo install cargo-tarpaulin

  # ---------------------------- 🧪 Testing Tasks 🧪 ----------------------------

  test:
    desc: "🧪 Run tests for both front-end and back-end"
    deps:
      - test:frontend
      - test:backend

  test:frontend:
    desc: "🧪 Run front-end tests"
    dir: web
    cmds:
      - pnpm test

  test:backend:
    desc: "🧪 Run back-end tests"
    dir: backend
    cmds:
      - cargo test

  # ---------------------------- 📊 Coverage Tasks 📊 ----------------------------

  coverage:frontend:
    desc: "📊 Generate coverage report for front-end tests"
    dir: web
    cmds:
      - pnpm run test:coverage
      - open coverage/index.html

  coverage:backend:
    desc: "📊 Generate coverage report for back-end tests"
    dir: backend
    cmds:
      - TS_RS_EXPORT_DIR="../web/src/bindings" cargo tarpaulin --out Html --output-dir coverage
      - open coverage/tarpaulin-report.html

  # ---------------------------- 🛠️ Development Mode 🛠️ ----------------------------

  dev:
    desc: "🚀 Start development servers for both front-end and back-end"
    deps:
      - dev:frontend
      - dev:backend

  dev:frontend:
    desc: "🚀 Start front-end development server"
    dir: web
    cmds:
      - pnpm run dev

  dev:backend:
    desc: "🚀 Start back-end development server"
    dir: backend
    cmds:
      - cargo run

  # ---------------------------- 🎨 Format Code 🎨 ----------------------------

  format:
    desc: "🎨 Format both front-end and back-end code"
    deps:
      - format:frontend
      - format:backend

  format:frontend:
    desc: "🎨 Format front-end code"
    dir: web
    cmds:
      - pnpm run format

  format:backend:
    desc: "🎨 Format back-end Rust code"
    dir: backend
    cmds:
      - cargo fmt -- --check --verbose

  # ---------------------------- 🌮 Check Code 🌮 ----------------------------

  check:
    desc: "🌮 Check front-end and back-end code"
    deps:
      - check:frontend
      - check:backend

  check:frontend:
    desc: "🌮 Check front-end code"
    dir: web
    cmds:
      - pnpm run lint

  check:backend:
    desc: "🌮 Check back-end code"
    dir: backend
    cmds:
      - cargo check
      - cargo clippy -- -D warnings

  # ---------------------------- 🏗️ Build for Production 🏗️ ----------------------------

  build:
    desc: "🏗️ Build both front-end and back-end for production"
    deps:
      - build:frontend
      - build:backend

  build:frontend:
    desc: "🏗️ Build front-end for production"
    dir: web
    cmds:
      - pnpm run build

  build:backend:
    desc: "🏗️ Build back-end for production"
    dir: backend
    cmds:
      - cargo build --release

  # ---------------------------- 🐳 Docker Management 🐳 ----------------------------

  docker:build:
    desc: "🐳 Build Docker image 'cirno'"
    cmds:
      - echo "🚧 Building Docker image 'cirno'..."
      - docker build -t cirno .

  docker:run:
    desc: "🚀 Run Docker container 'cirno' in detached mode"
    cmds:
      - echo "🚀 Starting Docker container 'cirno' on port 8000..."
      - |
        docker run -d \
          --network bridge \
          -p 8000:8000 \
          --name cirno_container \
          --env-file .env.production \
          cirno

  docker:stop:
    desc: "🛑 Stop and remove Docker container 'cirno_container'"
    cmds:
      - echo "🛑 Stopping Docker container 'cirno'..."
      - docker stop cirno_container
      - docker rm cirno_container

  docker:clean:
    desc: "🧹 Remove Docker image 'cirno'"
    cmds:
      - echo "🧹 Removing Docker image 'cirno'..."
      - docker rmi cirno

  # ---------------------------- 🧹 Clean Build Artifacts 🧹 ----------------------------

  clean:
    desc: "🧹 Clean all build artifacts for front-end, back-end, and Docker"
    deps:
      - clean:frontend
      - clean:backend
      - clean:docker

  clean:frontend:
    desc: "🧹 Clean front-end build artifacts"
    dir: web
    cmds:
      - rm -rf dist
      - rm -f tsconfig.app.tsbuildinfo
      - rm -f tsconfig.node.tsbuildinfo

  clean:backend:
    desc: "🧹 Clean back-end build artifacts"
    dir: backend
    cmds:
      - rm -rf target

  clean:docker:
    desc: "🧹 Remove Docker image 'cirno'"
    cmds:
      - docker rmi cirno

  clean:media-files:
    desc: "🧹 Remove all media files under /backend/tmp folder"
    dir: backend
    cmds:
      - rm -rf tmp/*

  # ---------------------------- 🔧 Tooling Tasks 🔧 ----------------------------

  generate-bindings:
    desc: "🔄 Generate bindings type files by cleaning and running backend tests"
    dir: web
    cmds:
      - echo "🧹 Cleaning web/src/bindings..."
      - rm -rf src/bindings/*
      - echo "🧪 Running backend tests to generate bindings..."
      - cd ../backend && cargo test

  create-database:
    desc: "🗂️ Create the SQLite database file by running the setup script"
    dir: backend/scripts
    cmds:
      - echo "📂 Running database setup script..."
      - ./create_db.sh

  check-database:
    desc: "🔍 Check and prepare database schema with sqlx"
    cmds:
      - |
        echo "📂 Setting DATABASE_URL for the database..."
        export DATABASE_URL="sqlite://$(pwd)/backend/database.db"
        echo "DATABASE_URL is set to: $DATABASE_URL"
        cd backend
        echo "🏗️ Running cargo sqlx prepare..."
        cargo sqlx prepare

  kill-backend:
    desc: "🔪 Kill any process running on port 8000"
    cmds:
      - |
        echo "🔍 Searching for process on port 8000..."
        pid=$(lsof -t -i :8000 || true)
        if [ -n "$pid" ]; then
          echo "💀 Killing process $pid on port 8000..."
          kill -9 $pid
          echo "✅ Process $pid killed successfully."
        else
          echo "🚫 No process found on port 8000."
        fi

  kill-frontend:
    desc: "🔪 Kill any process running on port 5173"
    cmds:
      - |
        echo "🔍 Searching for process on port 5173..."
        pid=$(lsof -t -i :5173 || true)
        if [ -n "$pid" ]; then
          echo "💀 Killing process $pid on port 5173..."
          kill -9 $pid
          echo "✅ Process $pid killed successfully."
        else
          echo "🚫 No process found on port 5173."
        fi

  count-lines:
    desc: "📊 Count lines of code excluding unnecessary files and directories"
    cmds:
      - |
        echo "📊 Counting lines of code..."
        cloc . \
        --exclude-dir=node_modules,target,dist,build,.git,vendor,logs,tmp,coverage \
        --exclude-ext=lock,tsbuildinfo \
        --not-match-f="(package-lock\.json|pnpm-lock\.yaml|Cargo\.lock)"
        echo "✅ Code line count completed."

  test-env:
    desc: "🧪 Test environment variables"
    cmds:
      - echo "GST_DEBUG_DUMP_DOT_DIR = $GST_DEBUG_DUMP_DOT_DIR"
      - echo "DATABASE_URL = $DATABASE_URL"
      - echo "VITE_API_URL = $VITE_API_URL"
  
  convert-dot:
    desc: "💻 Convert GST_DEBUG_DOT_DIR files to SVG"
    cmds:
      - echo "💻 Converting GST_DEBUG_DOT_DIR files to SVG..."
      - dot -Tsvg $GST_DEBUG_DUMP_DOT_DIR/pipeline.dot > $GST_DEBUG_DUMP_DOT_DIR/pipeline.svg
      - echo "✔️ GST_DEBUG_DOT_DIR files converted to SVG."
