// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";
import type { TaskType } from "./TaskType";

export type AsyncTaskResponse<T = null> = { task_id: TaskId, task_type: TaskType, payload: T | null, };
