// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Episode = {
  title: string | null
  original_title: string | null
  plot: string | null
  nfo_path: string | null
  video_file_path: string
  subtitle_file_path: string | null
  thumb_image_url: string | null
  thumb_image: string | null
  episode_number: string | null
  runtime: string | null
}
