// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EpisodeDTO = {
  id: bigint
  title: string | null
  original_title: string | null
  plot: string | null
  nfo_path: string | null
  video_file_path: string
  subtitle_file_path: string | null
  thumb_image_url: string | null
  thumb_image: string | null
  season_number: bigint | null
  episodes_number: bigint | null
  runtime: bigint | null
}
