// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryCategory } from "./LibraryCategory";
import type { LibraryPoster } from "./LibraryPoster";
import type { LibraryStatus } from "./LibraryStatus";

export type LibraryDto = { id: bigint, name: string, category: LibraryCategory, directory: string, posters: Array<LibraryPoster>, item_count: bigint, last_scanned: string | null, current_status: LibraryStatus, auto_scan: boolean, error: string | null, storage_used: bigint, health_score: bigint, created_at: string, updated_at: string, };
