// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskIdentifier } from "./TaskIdentifier";

export type LibrarySaved = { type: string, task_identifier: TaskIdentifier, library_id: bigint, library_name: string, };
