// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Library } from "./Library";
import type { TaskIdentifier } from "./TaskIdentifier";

export type LibraryScanned = { type: string, task_identifier: TaskIdentifier, library: Library, };
