// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryCategory } from "./LibraryCategory";
import type { LibraryPoster } from "./LibraryPoster";

export type LibraryDto = { id: bigint, name: string, category: LibraryCategory, directory: string, posters: Array<LibraryPoster>, };
