// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Library } from "./Library";
import type { TaskIdentifier } from "./TaskIdentifier";

export type LibraryEventType = { "LibraryScanned": { task_identifier: TaskIdentifier, library: Library, } } | { "LibrarySaved": { task_identifier: TaskIdentifier, library_id: bigint, library_name: string, } };
