// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaLibrary } from "./MediaLibrary";
import type { TaskIdentifier } from "./TaskIdentifier";

export type MediaLibraryScanned = { type: string, task_identifier: TaskIdentifier, media_library: MediaLibrary, };
