// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaActor } from "./MediaActor";

export type MediaItemDto = { id: bigint, title: string, plot: string | null, poster_path: string | null, fanart_path: string | null, country: string | null, year: string | null, genres: Array<string>, actors: Array<MediaActor>, };
