// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaLibrary } from "./MediaLibrary";

export type MediaLibraryEventType = { "MediaLibraryScanned": MediaLibrary } | { "MediaLibrarySaved": { media_library_id: bigint, media_library_name: string, } };
