// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TvShow } from "./TvShow";

export type MediaLibrary = { tv_show: Array<TvShow>, };
