// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaLibraryCategory } from "./MediaLibraryCategory";
import type { MediaLibraryPoster } from "./MediaLibraryPoster";

export type MediaLibraryDto = { id: bigint, name: string, category: MediaLibraryCategory, posters: Array<MediaLibraryPoster>, };
