// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskIdentifier } from "./TaskIdentifier";

export type MediaLibrarySaved = { type: string, task_identifier: TaskIdentifier, media_library_id: bigint, media_library_name: string, };
