// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaActor = { name: string | null, role: string | null, thumb: string | null, profile: string | null, tmdb_id: string | null, };
