// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaLibraryCategory } from "./MediaLibraryCategory";

export type SaveMediaLibraryPayload = { name: string, directory: string, category: MediaLibraryCategory, };
