// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodeDto } from "./EpisodeDto";

export type SeasonDto = { season_number: bigint | null, season_title: string | null, episodes: Array<EpisodeDto>, };
