// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodeDTO } from "./EpisodeDTO";

export type SeasonDTO = { season_number: bigint | null, season_title: string | null, episodes: Array<EpisodeDTO>, };
