// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";

export type Season = { title: string | null, show_title: string | null, sort_title: string | null, year: string | null, plot: string | null, tvdb_id: string | null, imdb_id: string | null, tmdb_id: string | null, wikidata_id: string | null, premiered: string | null, season_number: number | null, description: string | null, nfo_path: string | null, episodes: { [key in number]?: Episode }, };
