// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";

export type TaskIdentifier = { task_id: TaskId, ws_client_id: string | null, };
