// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TVSeriesDTO = { id: bigint, title: string, plot: string | null, poster_path: string | null, fanart_path: string | null, country: string | null, year: string | null, genres: Array<string>, };
