// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryCategory } from "./LibraryCategory";

export type UpdateLibraryPayload = { id: number, name: string, directory: string, category: LibraryCategory, };
