// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { System } from "./System";

export type WebSocketMessage = { "System": System };
