// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parser } from "./Parser";
import type { PipelineAction } from "./PipelineAction";
import type { System } from "./System";

export type WebSocketMessage = { "PipelineAction": PipelineAction } | { "System": System } | { "Parser": Parser };
